#!/bin/bash

# This file needs to be sourced by your .bashrc in order for the Comoto CLI to work correctly

# Add moto script to path
export COMOTO_CLI_DIR="$JJC_CONFIG_DIR/moto"
export PATH="$COMOTO_CLI_DIR":$PATH

# Set up github cli command completion
eval "$(gh completion -s bash)"

# TODO move this to inside moto script
complete -W "$(ls $COMOTO_CLI_DIR/command)" moto
