#!/bin/bash

# https://github.com/icy/bash-coding-style#function-names

export COMOTO_CLI_DIR="$JJC_CONFIG_DIR/moto"

export PATH="$COMOTO_CLI_DIR/lib":$PATH

subcommands=$COMOTO_CLI_DIR/lib

# TODO move to helpers
# TODO Then remove the export
_comoto_cli_app_name() {
  case $1 in
    cg) echo "cycle-gear-redline-webapp" ;;
    jp) echo  "jp-cycles-redline-webapp" ;;
    rz) echo   "revzilla-redline-webapp" ;;
    *) return 1
  esac
  return 0
}
export -f _comoto_cli_app_name

export COMOTO_CLI_MONOREPO_DIR=~/monorepo

_parse_params() {

  while :; do
    case "${1-}" in
    -h | --help) usage ;;
    logs)
      shift
      $subcommands/logs $@
      exit $?;;
    repl)
      shift
      $subcommands/repl $@
      exit $?;;
    bounce)
      shift
      $subcommands/bounce $@
      exit $?;;
    check)
      shift
      $subcommands/check $@
      exit $?;;
    -?*) die "Unknown option: $1" ;;
    *) break ;;
    esac
    shift
  done

  # args=("$@")
  # check required params and arguments
  # [[ -z "${param-}" ]] && die "Missing required parameter: param"
  # [[ ${#args[@]} -eq 0 ]] && die "Missing script arguments"
  return 0
}

_parse_params "$@"

exit 0
