#!/bin/bash

# https://github.com/icy/bash-coding-style#function-names
# TODO add to healthcheck: bash 4+
# TODO see https://revzilla.atlassian.net/wiki/spaces/TECH/pages/338919566/Kubernetes+and+Google+Cloud+-+Getting+Started
# TODO https://github.com/revzilla/monorepo/wiki/Dev-Ops

export COMOTO_CLI_DIR="$JJC_CONFIG_DIR/moto"

# TODO no need to export since this var is already exported?
export PATH="$COMOTO_CLI_DIR/command":$PATH

# TODO this can / should come before above statement
command_dir=$COMOTO_CLI_DIR/command

# TODO move to ./lib
# TODO Then remove the export
_comoto_cli_app_name() {
  case $1 in
    cg) echo "cycle-gear-redline-webapp" ;;
    jp) echo  "jp-cycles-redline-webapp" ;;
    rz) echo   "revzilla-redline-webapp" ;;
    *) return 1
  esac
  return 0
}
export -f _comoto_cli_app_name

export COMOTO_CLI_MONOREPO_DIR=~/monorepo

echo_help() {
  echo "TODO: flesh out this help message"
  exit 0
}

# Maybe show help
[[ $# -eq 0 ]] && echo_help
[[ $# -eq 1 &&  $1 =~ ^(-h|--help)$  ]] && echo_help

# Run command if valid or throw error
potential_command_path=$command_dir/$1
if [[ -e $potential_command_path ]] ; then
  shift
  $potential_command_path $@
else
  echo "TODO: print error message" >&2
fi
