#!/bin/bash

print_and_eval_command() {

  if [ $1 = "--include-type" ] ; then
    cmd=$2
    maybe_type="\n$(type $2)\n"
  else
    cmd=$1
    maybe_type=""
  fi

  echo -e "\nExecuting:\n\n\t$cmd\n$maybe_type"

  eval $cmd
}

source $COMOTO_CLI_MONOREPO_DIR/zlaverse/support/bash_functions.sh

# TODO make a copy of those functions
# get helpful functions for printing in color
source $COMOTO_CLI_DIR/../_setup/helpers.sh
