#!/bin/bash

# https://github.com/icy/bash-coding-style#function-names
# TODO add to healthcheck: bash 4+
# TODO see https://revzilla.atlassian.net/wiki/spaces/TECH/pages/338919566/Kubernetes+and+Google+Cloud+-+Getting+Started
# TODO https://github.com/revzilla/monorepo/wiki/Dev-Ops

export COMOTO_CLI_DIR="$JJC_CONFIG_DIR/moto"

# TODO no need to export since this var is already exported?
export PATH="$COMOTO_CLI_DIR/command":$PATH

# TODO this can / should come before above statement
subcommands=$COMOTO_CLI_DIR/command

# TODO move to ./lib
# TODO Then remove the export
_comoto_cli_app_name() {
  case $1 in
    cg) echo "cycle-gear-redline-webapp" ;;
    jp) echo  "jp-cycles-redline-webapp" ;;
    rz) echo   "revzilla-redline-webapp" ;;
    *) return 1
  esac
  return 0
}
export -f _comoto_cli_app_name

export COMOTO_CLI_MONOREPO_DIR=~/monorepo

_parse_params() {

  while :; do
    case "${1-}" in
      -h | --help) usage ;;
      logs)
        shift
        $subcommands/logs $@
        exit $?;;
      repl)
        shift
        $subcommands/repl $@
        exit $?;;
      db)
        shift
        $subcommands/db $@
        exit $?;;
      bounce)
        shift
        $subcommands/bounce $@
        exit $?;;
      check)
        shift
        $subcommands/check $@
        exit $?;;
      *) break ;;
    esac
    shift
  done

  # args=("$@")
  # check required params and arguments
  # [[ -z "${param-}" ]] && die "Missing required parameter: param"
  # [[ ${#args[@]} -eq 0 ]] && die "Missing script arguments"
  return 0
}

_parse_params "$@"

exit 0
