#?/bin/bash

# GIT BASHRC

. $JJC_CONFIG_LIB/headers

gst() {
  clear
  for cmd in 'git status' 'git latest' 'gh pr checks' ; do
    # TODO combine this into one 'print_and_eval' function
    print_headerrr "$cmd"
    eval "$cmd"
  done
  echo
}
