#!/bin/bash

# GIT SETUP
#
# To use this file, create a master config file at ~/.gitconfig:
# [user]
#     email = <my email>
#     name = Jonathan Chukinas
# [include]
#     path = .gitconfig_shared
#
# Then create a symlink to this file

script_dir="$( cd -- "$( dirname -- "${BASH_SOURCE[0]:-$0}"; )" &> /dev/null && pwd 2> /dev/null; )";
source $script_dir/../_setup/helpers.sh

# Start Main Script
###################

print_header 'GIT'

# TODO I don't like this being directly in the config
# use symlinking instead?
# how though then to have different settings per computer (e.g. email)?
print_subheader 'set global config'
git config --global user.name     "chukinas"
git config --global include.path  $script_dir/gitconfig
echo
echo '~/.gitconfig:'
echo
cat ~/.gitconfig

bash $script_dir/setup_gh_cli

