#!/bin/bash

# . ./bashrc/setup.sh

script_dir="$( cd -- "$( dirname -- "${BASH_SOURCE[0]:-$0}"; )" &> /dev/null && pwd 2> /dev/null; )";
JJC_CONFIG_DIR=$(readlink -f $script_dir)

source $JJC_CONFIG_DIR/_setup/helpers.sh

clear
echo
print_subheader $script_dir/setup

echo "About to update apt & apt-get"
# NOTE: apt is the newer one
# https://itsfoss.com/apt-vs-apt-get-difference/
sudo apt update
sudo apt-get update

bash $script_dir/git/setup
bash $script_dir/ack/setup
bash $script_dir/asdf/setup
# TODO rename this dir to nvim
bash $script_dir/neovim/setup
