#!/bin/bash

. $COMOTO_PROJECT_ROOT/etl/scripts/bash_functions.sh
alias etl-restart="cd $COMOTO_PROJECT_ROOT/etl && docker-compose stop && docker-compose up -d && etl-log"
alias etl-check="\
  etl-credo \ &&
  etl-test \ &&
  etl-dialyzer \
"

function etl-rebase() {
  (
    comoto_cli cd etl
    git rebaseontolatestmaster main && git latest
  )
}
# alias etl-fort="sudo nano /etc/resolv.conf"

# Recommended by Owen (SmartLogic)
export KERL_CONFIGURE_OPTIONS='--disable-debug --withoutjavac'
export ODS_URL='ecto://sql_etl_stg_read:0d5_3tL_r3aD-5tG@jpcods01stg.systems.maggroup.com:1433/ODS_TO_ADMIN?ssl=true'
export REDLINE_URL='ecto://postgres:PG92d3vp%40assw0rd@postgres/ecom'
export GHOST_EXPORT_PATH="$HOME/Downloads/common-tread.ghost.*.json"
