#!/bin/bash

. $COMOTO_PROJECT_ROOT/etl/scripts/bash_functions.sh
image_processing_root="$COMOTO_PROJECT_ROOT/image_processing"
alias ipcd='cd $COMOTO_PROJECT_ROOT/image_processing'

function ipnote() {
  if [[ $# -eq 0 ]] ; then
    cat $image_processing_root/README.md
  else
    echo "$*" >> $image_processing_root/README.md
  fi
}
