#!/bin/bash

. $COMOTO_PROJECT_ROOT/etl/scripts/bash_functions.sh
alias jrmsbounce="cd $COMOTO_PROJECT_ROOT/etl && docker-compose stop && docker-compose up -d && etl-log"
alias jrmscheck="\
  etl-credo \ &&
  etl-test \ &&
  etl-dialyzer \
"
alias jrmsrebase="git rebaseontolatestmaster main && git latest"
alias jrmsfort="sudo nano /etc/resolv.conf"
