#!/bin/bash

. $JJC_CONFIG_LIB/headers

# TODO move all the other comoto / monorepo stuff into here
# TODO move the datagrip stuff in here
# TODO is there any other dir that is only used on Comoto machines?

# MONOREPO SETUP
################

print_header 'Comoto Stuff'
# TODO move this to moto setup?
print_subheader Monorepo

