#!/bin/bash

_comoto_cli_command_usage() {
  cat <<EOF

Usage: comoto_cli bash [OPTIONS] CONTAINER_SHORT_NAME

Open a terminal to a container

Options:
  -h, --help  Print this help and exit

Container Short Names:
  cg          Cycle Gear
  jp          J&P Cycles
  rz          RevZilla

EOF
}

_comoto_cli_command_args="cg jp rz"

_comoto_cli_command_execute() {
  command='comoto_cli bash'
  . $COMOTO_CLI_ROOT/lib/print $command
  . $COMOTO_PROJECT_ROOT/monorepo/zlaverse/support/bash_functions.sh

  # TODO add autocomplete
  # TODO error out when given an invalid $1

  case $1 in
    -h | --help) _comoto_cli_command_usage; return 0;;
    cg|jp|rz) subcommand="$1-bash" ;;
    *) echo "TODO this is error msg" >&2 && exit 1
  esac

  print_and_eval_command --include-type "$subcommand"
}

_comoto_cli_command_completion() {
  local cur_arg="${COMP_WORDS[2]}"
  case $COMP_CWORD in
    2)
      COMPREPLY=( $(compgen -W "$_comoto_cli_command_args" -- "$cur_arg") )
      ;;
    *) ;;
  esac
}
