#!/bin/bash

. $COMOTO_CLI_LIB/print

_comoto_cli_command_summary='Restart containers'
_comoto_cli_command_usage='comoto_cli bounce [OPTIONS]'

# TODO it would be nice to have a -v|--volumes flag that takes a type of volume to drop
#   -redline_build
#   -redline_deps
#   -javascript
_comoto_cli_help() {
  print_help_h2 'Options'
  print_help_li '-h                        Print this help and exit'
  print_help_li '-s [CONTAINER SHORT NAME] bounce just a single [S]ite; otherwise do all'
  print_help_li '-b                        remove redline/_build dir'
  print_help_li '                             This can fill up with junk eventually'
  print_help_li '-a                        Run [A]nsible setup before anything else'
  print_help_li "                             This isn't usually required,"
  print_help_li "                             but if the normal bounce isn't working,"
  print_help_li "                             include this step as a nuclear option."
  print_help_li '-j                        Drop javascript asset volumes'
  print_help_h2 'Container Short Names'
  print_help_li 'cg          Cycle Gear'
  print_help_li 'jp          J&P Cycles'
  print_help_li 'rz          RevZilla'
  print_help_li 'redline     All three above'
}

_comoto_cli_command_completion() {
  local valid_opts="-h -a -s"
  local valid_site_args="cg jp rz redline"
  local current_word="${COMP_WORDS[$COMP_CWORD]}"
  COMPREPLY=( $(compgen -W "$valid_opts" -- "$current_word") )
}


# TODO add --help back in


_comoto_cli_execute() {
  local what_to_bounce=all
  local do_ansible=1
  local do_remove_redline_build=""
  local do_remove_assets_build=false
  local docker_volumes_to_remove=()

  OPTIND=1
  while getopts "habjs:" opt; do
    case $opt in
      h)
        $COMOTO_CLI_LIB/render_help
        return 0
        ;;
      a) do_ansible=0;;
      j) do_remove_assets_build=true;;
      b) do_remove_redline_build=1;;
      s)
        what_to_bounce=$OPTARG
        ;;
      *) echo "$0: error" >&2; return 1
    esac
  done

  if [[ $do_ansible = 0 ]]
  then
    (
      # Add stuff at top of script to throw error if this does not exist
      cd $ZV_DEV
      ./linux-setup.sh
    )
  fi

  if [[ -n $do_remove_redline_build ]]
  then
    (
      comoto_cli cd redline
      # rm -rf _build
    )
  fi

  if [[ $do_remove_assets_build = true ]]
  then
    sites=(cg jp rz)
    child_apps=(sp ws) # store portal and webstore
    for site in ${sites[@]}; do
      for child_app in ${child_apps[@]}; do
        volume="zla_$site-$child_app-node"
        docker_volumes_to_remove+=($volume)
      done
    done
  fi

  # TODO add in a flag for removing redline build volumes
  # docker volume rm zla_cg-build zla_jp-build zla_rz-build;
  cmd_remove_volumes=''
  if [[ ${!docker_volumes_to_remove[@]} -gt 0 ]]
  then
    cmd_remove_volumes="docker volume rm ${docker_volumes_to_remove[@]};"
  fi

  echo "What to bounce: ${what_to_bounce}"

  case $what_to_bounce in
    cg)
      if container_name=$($COMOTO_CLI_LIB/container_name -z cg) ; then
        subcommand="docker restart $container_name && comoto_cli logs cg"
      else
        print_usage_error
        exit 1
      fi
      ;;
    jp)
      if container_name=$($COMOTO_CLI_LIB/container_name -z jp) ; then
        subcommand="docker restart $container_name && comoto_cli logs jp"
      else
        print_usage_error
        exit 1
      fi
      ;;
    rz)
      if container_name=$($COMOTO_CLI_LIB/container_name -z rz) ; then
        subcommand="docker restart $container_name && comoto_cli logs rz"
      else
        print_usage_error
        exit 1
      fi
      ;;
    redline)
      subcommand="docker restart $($COMOTO_CLI_LIB/container_name -z cg) $($COMOTO_CLI_LIB/container_name -z jp) $($COMOTO_CLI_LIB/container_name -z rz) && comoto_cli logs"
      ;;
    all)
      subcommand="\
        (comoto_cli cd monorepo && docker-compose down && docker-compose pull && $cmd_remove_volumes docker-compose up -d --scale message-failure-service=1) && \
        comoto_cli migrate -u && \
        cg-load-test-schema && \
        comoto_cli logs"
      ;;
    *)
      print_usage_error
      exit 1
  esac

  print_and_eval_command "$subcommand"
}
