#!/bin/bash

. $COMOTO_CLI_LIB/print

_comoto_cli_command_summary='Change directory to commonly-used paths like redline and ecom'
_comoto_cli_command_usage='comoto_cli cd [OPTIONS] PATH_SHORT_NAME'

_comoto_cli_help() {
  cat <<EOF

Options:
  -h, --help  Print this help and exit
  -t          Echo command text only
  -p, --path  Echo the path instead of changing directory
              (Not yet implemented)

Path Short Names:
  comoto    $COMOTO_PROJECT_ROOT
  monorepo  $COMOTO_PROJECT_ROOT/monorepo
  ecom      $COMOTO_PROJECT_ROOT/monorepo/ecom
  redline   $COMOTO_PROJECT_ROOT/monorepo/redline
  zla       $COMOTO_PROJECT_ROOT/monorepo/zlaverse/dev
  etl       $COMOTO_PROJECT_ROOT/etl
EOF

  echo
  print_help_h2 'Examples'
  print_help_ex 'comoto_cli cd monorepo   # cd into the monorepo dir'
  echo
}

# TODO maybe there shouldn't be a 'path' command. Maybe it should be replaced with -p option in the 'cd' command
# TODO when I do that, I'll have to rework the option handling
# TODO either way, lots of repetition right now

_comoto_cli_command_completion() {
  unset _comoto_cli_command_completion
  . $COMOTO_CLI_ROOT/command/path
  _comoto_cli_command_completion $*
}

_comoto_cli_execute() {
  local text_only='false'

  while :; do
    case "${1-}" in
      -h|--help) $COMOTO_CLI_LIB/render_help; return 0;;
      -t) text_only='true' ;;
      *) break ;;
    esac
    shift
  done

  if [[ $# -ne 1 ]]; then
    print_usage_error
    return 1
  fi

  local cmd path
  if [[ $# -eq 1 ]] && path=$(comoto_cli path "$1" 2>/dev/null) ; then
    cmd="cd $path"
  else
    print_usage_error
    return 1
  fi

  if [[ $text_only == 'true' ]] ; then
    echo $cmd
  else
    print_and_eval_command "$cmd"
  fi
}
