#!/bin/bash

. $COMOTO_CLI_ROOT/lib/print

_comoto_cli_command_summary='Quality-control your code locally, before it gets to Circle CI'
_comoto_cli_command_usage='comoto_cli check [OPTIONS] [CHECKS]'

_comoto_cli_command_help() {
  cat <<EOF

Options:
  -h, --help      Print this help and exit

Checks:
  credo
  dialyzer        (not yet implemented)

Examples
  comoto_cli check                  # Run all (both credo and dialyzer)
  comoto_cli check credo            # Run credo only
  comoto_cli check dialyzer         # Run dialyzer only
  comoto_cli check credo dialyzer   # Run both credo and dialyzer
  comoto_cli check -h               # Print this help message
  comoto_cli check --help           # Print this help message

All checks are run in the local rz container.

EOF
# TODO add examples to the main comoto_cli help
}

_credo() {
  # TODO copy this pattern to the other scripts
  # TODO can `mix credo` be in single quotes?
  # TODO I don't think the cd is necessary
  # TODO add the rz-repl to comoto_cli

  comoto_cli bash rz 'mix credo'

  credo_exit_code=$?

  echo
  if [[ ! $credo_exit_code -ne 0 ]]
  then
    print_success 'Credo check succeeded'
  else
    print_fail 'Credo check failed'
  fi

  return $credo_exit_code
}

_dialyzer() {
  echo "TODO: implement the dialyzer check"
  :
}

_comoto_cli_command_execute() {
  # TODO typing 'm check -he' should produce an error, but credo runs anyway
  # TODO implement the credo and dialyzer args
  _credo && _dialyzer
}

_comoto_cli_command_completion() {
  :
}
