#!/bin/bash

# Usage: moto check

# Catch errors locally that would stop a Circle CI workflow.
# Dialyzer and Credo

echo "sourcing check"

. $COMOTO_CLI_ROOT/lib/print

echo "still u"

_comoto_cli_command_usage() {
  echo "Usage: comoto_cli check"
}

echo "still e"

_comoto_cli_command_error() {
  _comoto_cli_command_usage >&2
}

echo "still c"

_credo() {
  # TODO copy this pattern to the other scripts
  # TODO can `mix credo` be in single quotes?
  # TODO I don't think the cd is necessary
  # TODO add the rz-repl to comoto_cli
  print_and_eval_command "comoto_cli cd monorepo && rz-bash 'mix credo'"

  credo_exit_code=$?

  echo
  if [[ ! $credo_exit_code -ne 0 ]]
  then
    print_success 'Credo check succeeded'
  else
    print_fail 'Credo check failed'
  fi

  return $credo_exit_code
}

echo "still d"

_dialyzer() {
  echo "TODO: implement the dialyzer check"
  :
}

echo "still ..."

_comoto_cli_command_execute() {
  echo "arg count: $#"
  # if [[ $# -ne 0 ]] ; then
  #   _comoto_cli_command_error
  #   exit 1
  # else
    _credo && _dialyzer
  # fi
}

_comoto_cli_command_completion() {
  :
}
