#!/bin/bash

_comoto_cli_command_summary='No-op for now, but will be the home for logging, bouncing, etc'
_comoto_cli_command_usage='comoto_cli db [OPTIONS] SETUP_COMMAND'

_comoto_cli_command_help() {
  cat <<EOF

Options:
  -h, --help      Print this help and exit

Subcommands:
  bash    Interact with a container's shell
  bounce  Restart containers
  log     View log output

Examples
  comoto_cli container bounce       # Restart all containers
  comoto_cli container bounce cg    # Restart the Cycle Gear container
  comoto_cli container log rz       # View local RevZilla logs
  comoto_cli container log --help   # Print help for the 'log' subcommand
  comoto_cli container -h           # Print this help message
  comoto_cli container --help       # Print this help message

EOF
}

_comoto_cli_command_execute() {
  echo >&2 'Not yet implemented'
  return 1
}
_comoto_cli_command_completion() {
  echo -n
}
