#!/bin/bash

. $COMOTO_CLI_LIB/print

_comoto_cli_command_summary='Set up your local database'
_comoto_cli_command_usage='comoto_cli db [OPTIONS] SUBCOMMAND'

_comoto_cli_help() {
  print_help_h2 'Options'
  print_help_li '-h, --help  Print this help and exit'

  print_help_h2 'Subcommands'
  print_help_li 'from_dump   Update local db with the latest dump from GCP'
  print_help_li 'reindex     Reindex Elasticsearch'
  print_help_li 'privileges  Elevate your user account privileges.'
  print_help_li '            Returns you the code to paste into datagrip'
  # TODO is this pw subcommand in the right place?
  print_help_li 'pw          Password for connecting to db in DataGrip'

  print_help_h2 'Examples'
  print_help_ex "comoto_cli db from_dump"
  print_help_ex "comoto_cli db reindex"
  print_help_ex "comoto_cli db privileges   # generates SQL code you can paste into datagrip"
}


# TODO extract this to lib
_comoto_cli_add_user_accounts() {
  # TODO this should be a function in redline that's called in an iex session
  local email_address='jonathan.chukinas@revzilla.com'
  if ! print_confirm "Is this your account address: $email_address?" ; then
    echo exiting >&2
    return 1
  fi
  if ! print_confirm "You must have created used accounts before executing. Have you?" ; then
    echo exiting >&2
    return 1
  fi
  echo
  echo "-- Make yourself an admin"
  echo "UPDATE users SET role_id = 2 WHERE email_address = '$email_address';"
  for site_id in 1 4 16
  do
    echo
    echo "-- give yourself permissions for site $site_id"
    echo "INSERT INTO user_permission_sections (user_id, permission_section_id, site_id)"
    echo "  SELECT (SELECT id FROM users WHERE email_address = '$email_address' and site_id = $site_id), ps.id, $site_id"
    echo "  FROM permission_sections ps;"
  done
  echo
}

_comoto_cli_command_completion() {
  local cur_word="${COMP_WORDS[$COMP_CWORD]}"
  COMPREPLY=( $(compgen -W "privileges from_dump reindex pw" -- "$cur_word"))
}

_comoto_cli_execute() {
  case "${1-}" in
    -h|--help) $COMOTO_CLI_LIB/render_help; return 0;;
    privileges)
      _comoto_cli_add_user_accounts
      return 0
      ;;
    pw)
      echo
      echo "copy and paste this password into datagrip:"
      echo
      gcloud auth print-access-token
      echo
      return 0
      ;;
    from_dump)
      $COMOTO_CLI_LIB/db_restore_from_latest_dump
      ;;
    reindex)
      $COMOTO_CLI_LIB/elasticsearch
      ;;
    *)
      # TODO error
      break
      ;;
  esac
}
