#!/bin/bash

. $COMOTO_CLI_LIB/print

_comoto_cli_command_summary='Build local monorepo docs'
_comoto_cli_command_usage='comoto_cli docs [OPTIONS]'

_comoto_cli_help() {
  print_help_h2 'Options'
  print_help_li '-h, --help  Print this help and exit'
}

_comoto_cli_command_completion() {
  local valid_args="-h --help"
  [[ $# -gt 1 ]] && return 1
  COMPREPLY=( $(compgen -W "$valid_args" -- "$1") )
}

_comoto_cli_execute() {
  $COMOTO_CLI_LIB/monorepo_local_docs build
}
