#!/bin/bash

. $COMOTO_CLI_ROOT/lib/print

_comoto_cli_command_usage() {
  print_help_h1 'Translate zla bash_functions to comoto_cli commands'
  print_help_h2 'Usage'
  print_help_li 'comoto_cli hist [ZLA_BASH_FUNCTION]'
  print_help_h2 'Options'
  print_help_li '-h, --help  Print this help and exit'
  print_help_h2 'Examples'
  print_help_li 'comoto_cli hist rz-bash  # ==> comoto_cli bash rz'
  print_help_li 'comoto_cli hist          # ==> cg-bash         comoto_cli bash cg'
  print_help_li '                         # ==>  ...             ...'
  print_help_li '                         # ==> rz-bash         comoto_cli bash rz'
  echo
}

_comoto_cli_command_execute() {
  clear
  _comoto_cli_command_usage
}
