#!/bin/bash

_comoto_cli_command_summary='Translate zla bash_functions to comoto_cli commands'
_comoto_cli_command_usage='comoto_cli hist [ZLA_BASH_FUNCTION]'

. $COMOTO_CLI_ROOT/lib/print

_comoto_cli_help() {
  print_help_h2 'Options'
  print_help_li '-h, --help  Print this help and exit'
  print_help_h2 'Examples'
  print_help_li 'comoto_cli hist rz-bash  # ==> comoto_cli bash rz'
  print_help_li 'comoto_cli hist          # ==> cg-bash         comoto_cli bash cg'
  print_help_li '                         # ==>  ...             ...'
  print_help_li '                         # ==> rz-bash         comoto_cli bash rz'
  echo
}

_comoto_cli_execute() {
  while :; do
    case "${1-}" in
      -h|--help) $COMOTO_CLI_ROOT/lib/render_help; return 0;;
      *) break ;;
    esac
    shift
  done
}
