#!/bin/bash

. $COMOTO_CLI_ROOT/lib/print

_comoto_cli_command_summary='View the logs for one or several containers'
_comoto_cli_command_usage='comoto_cli logs [OPTIONS] [CONTAINERS]'

_comoto_cli_command_help() {
  cat <<EOF

Options:
  -h, --help      Print this help and exit
  -t, --tail      Number of lines to print initially (default: 10)
                  (Not yet implemented)

Containers:
  cg
  jp
  rz

Examples
  comoto_cli logs           # View all logs (All redline apps, ecom, services, etc)
  comoto_cli logs cg        # View logs for Cycle Gear
  comoto_cli logs redline   # View logs for all redline apps (i.e cg, jp, rz)
  comoto_cli logs cg rz     # View logs for Cycle Gear and RevZilla
  comoto_cli logs -h        # Print this help
  comoto_cli logs --help    # Print this help

EOF
}

# TODO should this be a subcommand for container?
#   It has the same completion as bounce too

_comoto_cli_command_completion() {
  unset _comoto_cli_command_completion
  . $COMOTO_CLI_ROOT/command/bounce
  _comoto_cli_command_completion $*
}

_comoto_cli_command_execute() {
  # defaults
  tail=10

  app_name="$($COMOTO_CLI_ROOT/lib/container_name $1)"

  case $? in
    0|1) ;;
    *) echo print_usage_error && exit 1
  esac

  print_and_eval_command "($(comoto_cli cd -t monorepo) && docker-compose logs -f --tail=$tail $app_name)"
}
