#!/bin/bash

. $COMOTO_CLI_ROOT/lib/print

_comoto_cli_command_summary='Migrate local copy of ecom database'
_comoto_cli_command_usage='comoto_cli migrate [OPTIONS] ACTIONS'

_comoto_cli_command_help() {
  cat <<EOF

Options:
  -h, --help      Print this help and exit
  -c              Confirm before executing command.
                  Useful for previewing a command before committing to it.

Actions:
  -d  Migrate Down
  -u  Migrate Up
  -l  Lock

Examples
  comoto_cli migrate -lu       # Lock migrations, then migrate up
  comoto_cli migrate -du       # Migrate down, then immediatedly up
  comoto_cli migrate -d -u     # Migrate down, then immediatedly up

EOF
}

# Accumulate rake tasks to be run in the local ecom shell
local rake_tasks=''
_add_db_migrate_task() {
  new_rake_task="rake db:migrate:$1"
  if [[ -z $rake_tasks ]] ; then
    rake_tasks="$new_rake_task"
  else
    rake_tasks="$rake_tasks && $new_rake_task"
  fi
}

_comoto_cli_command_completion() {
  local cur_word="${COMP_WORDS[$COMP_CWORD]}"
  COMPREPLY=( $(compgen -W "-h --help -c -d -u -l" -- "$cur_word"))
}

_comoto_cli_command_execute() {
  local confirmation_option='-C'

  while getopts "hcdlu" opt; do
    case $opt in
      # TODO right now, the --help doesn't work
      h) $COMOTO_CLI_ROOT/lib/render_help;;
      c) confirmation_option='-c';;
      d) _add_db_migrate_task 'down';;
      l) _add_db_migrate_task 'lock';;
      u) _add_db_migrate_task 'up';;
      # TODO add a usage function
      *) print_usage_error && exit 1
    esac
  done

  print_and_eval_command $confirmation_option "comoto_cli bash ecom '$rake_tasks'"
}
