#!/bin/bash

. $COMOTO_CLI_ROOT/lib/ansi_color

_comoto_cli_command_summary='Generate fully-qualified paths to common projects'
_comoto_cli_command_usage='comoto_cli path [OPTIONS] PATH_SHORT_NAME'

# TODO move this to a lib file
_help_header() {
  text=$(echo $1 | tr '[:lower:]' '[:upper:]' )
  echo -e "${boldon}${text}:${reset}"
}

# TODO move this to a lib file
_indent_print() {
  echo -e "  $*"
}

# TODO follow this strategy in other commands
_comoto_cli_command_help() {
  local comoto_project_root=${COMOTO_PROJECT_ROOT:-"${redf}\$COMOTO_PROJECT_ROOT${reset}"}
  # TODO this should be added to a "checkhealth function"
  if [[ -d $COMOTO_PROJECT_ROOT ]] ; then
    local your_project_root_msg="${greenf}${boldon}SUCCESS:${boldoff} \$COMOTO_PROJECT_ROOT is set to $COMOTO_PROJECT_ROOT${reset}"
  else
    local your_project_root_msg="${redf}${boldon}ERROR:${boldoff} \$COMOTO_PROJECT_ROOT is not set to a valid directory.${reset}"
  fi

  echo
  _help_header 'Prerequisite'
  _indent_print '$COMOTO_PROJECT_ROOT environment variable points to directory containing the monorepo.'
  _indent_print $your_project_root_msg
  echo
  _help_header 'Options'
  _indent_print '-h, --help  Print this help and exit'
  echo
  _help_header 'Path Short Names'
  _indent_print "comoto      $comoto_project_root"
  _indent_print "monorepo    $comoto_project_root/monorepo"
  _indent_print "ecom        $comoto_project_root/monorepo/ecom"
  _indent_print "redline     $comoto_project_root/monorepo/redline"
  _indent_print "zla         $comoto_project_root/monorepo/zlaverse/dev"
  echo
  _help_header 'Examples'
  _indent_print "comoto_cli path ecom   # echos out '$(comoto_cli path ecom)'"
  echo
}

# TODO implement a way to add another argument to drill down into the main dir
# TODO should I retool this to set a $COMOTO_CLI_CUR_PATH ?
# TODO should `cd` depend on this?
# TODO rename _comoto_cli_path_execute

_comoto_cli_command_execute() {
  local current_command="comoto_cli path"
  local where_to=$1

  # TODO now that this is a function, these out functions are exposed...
  # TODO decouple this from my personal config script
  . $COMOTO_CLI_ROOT/lib/print "$current_command"

  while :; do
    case "${1-}" in
      -h|--help) $COMOTO_CLI_ROOT/lib/render_help; return 0;;
      *) break ;;
    esac
    shift
  done

  if [[ $# -ne 1 ]]; then
    print_usage_error
    exit 1
  fi

  case "$where_to" in
    comoto)   target="$COMOTO_PROJECT_ROOT";;
    monorepo) target="$COMOTO_PROJECT_ROOT/monorepo";;
    ecom)     target="$COMOTO_PROJECT_ROOT/monorepo/ecom";;
    redline)  target="$COMOTO_PROJECT_ROOT/monorepo/redline";;
    zla)      target="$COMOTO_PROJECT_ROOT/monorepo/zlaverse/dev";;
    *)
      print_usage_error
      exit 1
  esac

  echo "$target"
}

_comoto_cli_command_completion() {
  [[ $# -gt 1 ]] && return 1
  COMPREPLY=( $(compgen -W "comoto monorepo ecom redline zla" -- "$1") )
}
