#!/bin/bash

_comoto_cli_command_help() {
  cat <<EOF

Usage: comoto_cli repl [OPTIONS] [CONTAINER_SHORT_NAME]

Start an Ruby or IEX session in a container

Options:
  -h, --help  Print this help and exit

Container Short Names:
  ecom        (ruby) Ecom
  cg          (IEx)  Cycle Gear
  jp          (IEx)  J&P Cycles
  rz          (IEx)  RevZilla

EOF
# TODO what's the actual name of the ruby repl?
}

_comoto_cli_command_execute() {
  . $COMOTO_CLI_ROOT/lib/print

  # TODO add autocomplete
  # TODO error out when given an invalid $1

  case $1 in
    # TODO is this correct or should this be in the "bash" command?
    ecom) subcommand="ecom-bash" ;;
    cg|jp|rz) subcommand="$1-iex" ;;
    *) echo "TODO: this is an error" >&2 && exit 1
  esac

  print_and_eval_command --include-type "$subcommand"
}

_comoto_cli_command_completion() {
  local valid_args="cg jp rz ecom"
  [[ $# -gt 1 ]] && return 1
  COMPREPLY=( $(compgen -W "$valid_args" -- "$1") )
}
