#!/bin/bash

. $COMOTO_CLI_LIB/print

_comoto_cli_command_summary='For making and reviewing changes to encrypted monorepo code'
_comoto_cli_command_usage='comoto_cli secrets [OPTIONS] (decrypt) | (encrypt PR_NUMBER)'

_comoto_cli_help() {
  print_help_h2 'Options'
  print_help_li '-h, --help  Print this help and exit'
  print_help_h2 'Subcommands'
  print_help_li 'decrypt     Pull latest master, then decrypt secret files'
  print_help_li 'encrypt     Re-encrypt secret files'
}

_comoto_cli_command_completion() {
  local valid_args="decrypt encrypt"
  [[ $# -gt 1 ]] && return 1
  COMPREPLY=( $(compgen -W "$valid_args" -- "$1") )
  # TODO add completion for the subcommands
}

_comoto_cli_execute() {
  while :; do
    case "${1-}" in
      -h|--help) $COMOTO_CLI_LIB/render_help; return 0;;
      *) break ;;
    esac
    shift
  done

  subcommand="$1"
  shift

  case $subcommand in
    decrypt)
      comoto_cli cd monorepo
      git getlastestmaster && ./k8s/decrypt_everything.sh
      ;;
    encrypt)
      if [[ $# -ne 1 ]] ; then
        print_usage_error
        exit 1
      fi
      declare -i pr_number=$1
      gh pr checkout $pr_number
      ./k8s/diff_encrypted.sh
      ;;
    *)
      print_usage_error
      exit 1
      ;;
  esac
}
