#!/bin/bash

# Usage: moto vc
#
#   Wrappers around git and gh commands.
#   Makes it easier to e.g.

. $COMOTO_CLI_ROOT/lib/print

usage() {
  echo 'Comoto CLI: Usage: comoto_cli vc <subcommand> <filter_string>'
}

error() {
  usage >&2
  exit 1
}

# TODO add completion for the subcommands
subcommand="$1"
shift

# TODO get rid of that nvim setting that doesn't un-visualize after indenting

# TODO add help that says that the filter string can include either the pr or jira number
# TODO add an echo that warns the user that they're not in the right dir (if that's the case)
case $subcommand in
  checkout|view)
    filter_string="$1"
    echo filter string: $filter_string
    if [[ $# -eq 1 && -n $filter_string ]]
    then
      comoto_cli cd monorepo
      # TODO handle better for when multiple results come back
      pr_number="$(gh pr list | grep $filter_string | cut -f1)"
      echo PR number: $pr_number
      gh pr $subcommand $pr_number
    else
      error
    fi
    ;;
  *)
    error
    ;;
esac
