#!/bin/bash

# TODO replace with ag (silver searcher)
# TODO would need to update my nvim config

script_dir="$( cd -- "$( dirname -- "${BASH_SOURCE[0]:-$0}"; )" &> /dev/null && pwd 2> /dev/null; )";
source $script_dir/../_setup/helpers.sh

print_header "ACK"

print_subheader $0

#######################################
# Make sure ack is installed

echo 'Looking for ack'
if ack --version &> /dev/null
then
  echo 'Found'
else
  echo 'ack not found. Installing.'
  sudo apt-get install ack
fi
if ack --version &> /dev/null
then
  print_success 'ack is installed'
else
  print_fail 'ack not installed'
fi

#######################################
# Create Symlink

# TODO replace the symlink with ACKRC env var
echo 'symlinking ackrc'
ln -sf $script_dir/ackrc $HOME/.ackrc
print_success '.ackrc symlinked'
# TODO I should actually check this
