#!/bin/bash

# FIX replace with ag (silver searcher)
# FIX would need to update my nvim config
# https://beyondgrep.com/feature-comparison

. $JJC_CONFIG_LIB/headers

command_name=ack
command_exists() { $JJC_CONFIG_LIB/command_exists $command_name; }

#######################################
# main script
#######################################

print_header $command_name

print_subheader $0

#######################################
# Make sure ack is installed

echo 'Looking for ack'
if command_exists
then
  echo 'Found'
else
  echo 'ack not found. Installing.'
  sudo apt-get install ack
fi

#######################################
# print result

report_on_installation $command_name

