#!/bin/bash

# fzf config
# https://github.com/junegunn/fzf

export FZF_DEFAULT_OPTS='--height 40%'

# alias fzf_path=$(which fzf)
# fzf()
# {
#   echo
#   echo "USAGE:"
#   echo 'Token   Match type                  Description                         '
#   echo 'sbtrkt  fuzzy-match                 Items that match sbtrkt             '
#   echo "'wild   exact-match (quoted)        Items that include wild             "
#   echo '^music  prefix-exact-match          Items that start with music         '
#   echo '.mp3$   suffix-exact-match          Items that end with .mp3            '
#   echo '!fire   inverse-exact-match         Items that do not include fire      '
#   echo '!^music inverse-prefix-exact-match  Items that do not start with music  '
#   echo '!.mp3$  inverse-suffix-exact-match  Items that do not end with .mp3     '
#   echo
#   fzf_path
# }

# Quickly open a config file from the command line
# fuzzy find a config file (neovim config or general config, i.e. this repo)
# and open it in my editor
vic()
{
  # TODO should this env var be exported?
  local all_config_dir=$HOME/projects/all_config
  cd $all_config_dir
  $VISUAL $(fzf)
  cd -
}
