#!/bin/bash

# my standardized way of checking to see if a program is already installed

# USAGE: $JJC_CONFIG_DIR/lib/command_exists <command_name>

command_name="$1"
# https://stackoverflow.com/questions/592620/how-can-i-check-if-a-program-exists-from-a-bash-script
command -v $command_name &> /dev/null
