#!bin/bash

# TODO rename this file. It's got more than just header stuff

. $JJC_CONFIG_DIR/lib/ansi_color

print_title() {
   echo -e $cyanf
   echo "##################################################"
   echo "##################################################"
   echo "### $1"
   echo "##################################################"
   echo "##################################################"
   echo -e "${reset}"
}

print_header() {
   echo -e $cyanf
   echo "##################################################"
   echo $1
   echo "##################################################"
   echo -e "${reset}"
}

print_subheader() {
   echo -e "$cyanf$boldon"
   echo $1
   echo "--------------------------------------------------"
   echo -en "${reset}"
}

print_success() {
   echo -e "${greenf}${boldon}SUCCESS. $1$reset\n"
}

print_fail() {
   echo -e "${redf}FAIL. $1$reset\n"
}

print_cmd() {
  echo -e "${bluef}$1$reset"
}

report_on_installation() {

  command_name="$1"
  pretty_print_name=$command_name

  while getopts "p:" opt; do
    case $opt in
      p) pretty_print_name=$OPTARG ;;
      *) echo "$0: error" >&2; exit 1
    esac
  done
  shift $((OPTIND-1))

  if $JJC_CONFIG_DIR/lib/command_exists $command_name
  then
    print_success "$pretty_print_name is installed"
  else
    print_fail "$pretty_print_name not installed"
  fi
}
