#!/bin/bash

# defaults
tail=10

app_name="$($COMOTO_CLI_DIR/lib/container_name $1)"
base_subcommand="comoto_cli cd monorepo && docker-compose logs -f --tail=$tail"

case $? in
  0) subcommand=$base_subcommand ;;
  # TODO Exit if that wasn't a proper abbreviation
  1) subcommand="$base_subcommand $app_name" ;;
  *) echo "TODO this is an epic fail!" >&2 && exit 1
esac

. $COMOTO_CLI_DIR/moto_helpers

print_and_eval_command "$subcommand"
