#!/bin/bash

. $COMOTO_CLI_DIR/moto_helpers

# TODO add autocomplete
# TODO error out when given an invalid $1

case $1 in
  ecom) subcommand="ecom-bash" ;;
  *) exit 1
esac

print_and_eval_command --include-type "$subcommand"
