#!/bin/bash

# Usage: moto vc
#
#   Wrappers around git and gh commands.
#   Makes it easier to e.g.

source $COMOTO_CLI_DIR/moto_helpers

# TODO add completion for the subcommands
subcommand="$1"
shift

# TODO get rid of that nvim setting that doesn't un-visualize after indenting

# TODO add help that says that the filter string can include either the pr or jira number
case $subcommand in
  checkout|view)
    filter_string="$1"
    if [[ $# -eq 1 && -n $filter_string ]]
    then
      comoto_cli cd monorepo
      pr_number="$(gh pr list | grep $filter_string | cut -f1)"
      gh pr $subcommand $pr_number
    else
      echo "TODO add better error message" >&2
    fi
    ;;
  *)
    echo "TODO add better error message" >&2
    exit 1
    ;;
esac
