#!/bin/bash

# Usage: moto vc
#
#   Wrappers around git and gh commands.
#   Makes it easier to e.g.

source $COMOTO_CLI_DIR/moto_helpers

# TODO add completion for the subcommands
subcommand="$1"
shift

case $subcommand in
  checkout)
    filter_string="$1"
    if [[ $# -eq 1 && -n $filter_string ]]
    then
      pr_number="$(gh pr list | grep $filter_string | cut -f1)"
      gh pr checkout $pr_number
    else
      echo "TODO add better error message" >&2
    fi
    ;;
  *)
    echo "TODO add better error message" >&2
    exit 1
    ;;
esac
