#!/bin/bash

#######################################
# 1. Install asdf
# 2. Add plugins
# 3. Install tools
#######################################

# Standard Setup
script_dir="$(dirname $0)";
source $script_dir/../_setup/helpers.sh

function install_asdf() {
   echo
   echo "Installing curl & git"
   sudo apt-get install curl git

   echo
   echo "Cloning asdf repo"
   git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.10.0

   echo
   echo "asdf will be available after restarting shell"
   exit_code=0
}

print_subheader $0
echo "Checking for asdf"

# if [[ asdf --version ]]; then
#    echo "asdf IS INstalled"
# else
#    echo "asdf not found"
echo "Removing current asdf install"
rm -rf ~/.asdf
install_asdf
# fi

# TODO check for asdf. if exists, update instead of just removing and redownloading. install the new programs takes forever!

# TODO move this to a second setup file
# for (cut -d' ' -f1 ~/.tool-versions)
cut -d' ' -f1 $script_dir/tool-versions | xargs -n 1 asdf plugin add

# Print success or failure
if [[ asdf --version ]]; then
   print_success "SUCCESS. asdf is installed"
else
   print_fail "FAIL. asdf not installed"
fi
echo

exit $exit_code
