#!/bin/bash

#######################################
# Install tools (e.g. elixir and neovim) via asdf
#######################################

# TODO replace this with the fuller version
script_dir="$(dirname $0)";

. $JJC_CONFIG_LIB/headers

# TODO make this dynamic
print_subheader $script_dir/setup_install_tools


echo 'Checking neovim'
asdf install neovim
report_on_installation -p neovim nvim

echo 'Checking fzf'
asdf install fzf
report_on_installation fzf

echo 'Checking lua'
asdf install lua
report_on_installation lua

echo 'Checking node'
# requires python
asdf install nodejs
report_on_installation node

echo 'Checking rust'
asdf install rust
report_on_installation cargo
report_on_installation rustc

echo 'Checking erlang'
asdf install erlang
report_on_installation erl

# From: https://github.com/asdf-vm/asdf-erlang#ubuntu-2004-lts
# sudo apt-get -y install build-essential autoconf m4 libncurses5-dev libwxgtk3.0-gtk3-dev libwxgtk-webview3.0-gtk3-dev libgl1-mesa-dev libglu1-mesa-dev libpng-dev libssh-dev unixodbc-dev xsltproc fop libxml2-utils libncurses-dev openjdk-11-jdk

echo 'asdf list'
asdf list
