#!/bin/bash

. $JJC_CONFIG_LIB/headers

command_name=asdf

function install_asdf() {
   echo "Removing current asdf install"
   rm -rf ~/.asdf

   echo
   echo "Installing curl & git"
   sudo apt-get install curl git

   echo
   echo "Cloning asdf repo"
   git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.10.0

   echo
   echo "asdf will be available after restarting shell"
   exit_code=0
}

#######################################
# start main script
#######################################

print_subheader 'install asdf and add plugins'

#######################################
# PART I: asdf is installed and updated to latest version
#######################################

#######################################
# install if not found

echo 'Looking for asdf'
if asdf --version &> /dev/null
then
   echo 'Found'
else
   echo 'Not found'
   install_asdf
fi

#######################################
# update

echo 'Updating'
asdf update

#######################################
# Confirm installation

report_on_installation $command_name

#######################################
# PART II: Install plugins
#######################################

echo 'adding plugins'
cut -d' ' -f1 $JJC_CONFIG_ROOT/asdf/tool-versions | xargs -n 1 asdf plugin add
# TODO how can I check that this was successful?
print_success 'plugins installed'
