#!/bin/bash

. $COMOTO_CLI_LIB/print

_comoto_cli_command_summary='No-op for now, but will be the home for logging, bouncing, etc'
_comoto_cli_command_usage='comoto_cli db [OPTIONS] SETUP_COMMAND'

# TODO add the ability to "shut down" just a single container to hopefully improve recompile times for the
# one that I'm actually interested in

_comoto_cli_help() {
  cat <<EOF

Options:
  -h, --help      Print this help and exit

Subcommands:
  focus   Pause Redline containers not in use to speed compile times on the current container
  bash    Interact with a container's shell
  bounce  Restart containers
  log     View log output
EOF

  echo
  print_help_h2 Examples
  print_help_ex "comoto_cli container bounce       # Restart all containers"
  print_help_ex "comoto_cli container bounce cg    # Restart the Cycle Gear container"
  print_help_ex "comoto_cli container log rz       # View local RevZilla logs"
  print_help_ex "comoto_cli container log --help   # Print help for the 'log' subcommand"
  print_help_ex "comoto_cli container -h           # Print this help message"
  print_help_ex "comoto_cli container --help       # Print this help message"
  echo
}

_comoto_cli_command_completion() {
  echo -n
}

_comoto_cli_execute() {
  $COMOTO_CLI_LIB/render_help
}
