#!/bin/bash

# defaults
tail=10

cd $COMOTO_CLI_MONOREPO_DIR

subcommand="docker-compose logs -f --tail=$tail $(_comoto_cli_app_name $1)"

source $COMOTO_CLI_DIR/moto_helpers

print_and_eval_command "$subcommand"
