#!/bin/bash

# HELPERS FOR PRINTING OUTPUT TO USER
#######################################

. $JJC_CONFIG_DIR/lib/ansi_color

if [[ -z "$1" ]]; then
  exit 0
else
  current_command="$1"
fi

print_info() {
  echo "$current_command: $1"
}

print_header() {
  echo ; print_info "$1"
}

# TODO move this into lib
print_confirm() {
  while true; do
    read -p "$current_command: $1 [Y/n] " yn
    case $yn in
        [Yy]* ) return 0;;
        [Nn]* ) return 1;;
        * ) echo "Please answer yes or no.";;
    esac
  done
}

# Print a command and then execute it.
print_exec() {
  echo "$current_command: Executing: \`$1\`"
  eval "$1"
}

