#!/bin/bash

# USAGE
#   $COMOTO_CLI_LIB/down_all_containers

dir_is_docker_repo() {
  dir=${1:?"comoto_cli internal implementation error: dir_is_docker_repo must be given a directory"}
  if [[ ! -d $dir ]]; then
    echo "dir_is_docker_repo must be given a valid directory" >&2
    return 1
  fi

  docker_compose_filenames=(docker-compose.yml docker-compose.yaml compose.yml compose.yaml)
  for filename in "${docker_compose_filenames[@]}"
  do
    if [[ -f $dir$filename ]]; then
      return 0
    fi
  done
  return 1
}

#######################################
# MAIN SCRIPT
#######################################

echo "DOWNING ALL THINGS"
for dir in $COMOTO_PROJECT_ROOT/*/; do
  if dir_is_docker_repo $dir ; then
    echo
    echo "DOWNING $dir"
    (cd $dir && docker-compose down)
  fi
done
