#!/bin/bash
set -Eeuo pipefail

query=$1
# docker exec -e PGPASSWORD='PG92d3vp@assw0rd' -u postgres zla_postgres_1 psql --host=localhost --tuples-only --no-psqlrc --quiet --no-align --command "$query" ecom

docker exec -e PGPASSWORD='PG92d3vp@assw0rd' -u postgres zla_postgres_1 psql --host=localhost --command "$query" ecom
