#!/bin/bash

# DESCRIPTION
#   echo out the pr-number of the current repo
#
# USAGE
#   $0 current

# MAIN SCRIPT
#######################################

# For now, there's only one available command, 'current'.
# More will be added later, but for now all we have to do is check for that arg
if [[ $1 == 'current' ]] ; then
  echo "$(gh pr view | grep '^number:' | head -n 1 | cut -f2)"
else
  exit 1
fi
