#!/bin/bash

# TODO combine this with $JJC_CONFIG_DIR/lib?
# TODO rename formatter?

# HELPERS FOR PRINTING OUTPUT TO USER
#######################################

. $JJC_CONFIG_DIR/lib/ansi_color

if [[ -n "$1" ]]; then
  current_command="$1: "
fi

print_info() {
  echo "${current_command}$1"
}

print_header() {
  echo ; print_info "$1"
}

# TODO move this into lib
print_confirm() {
  while true; do
    read -p "${current_command}$1 [Y/n] " yn
    case $yn in
        [Yy]* ) return 0;;
        [Nn]* ) return 1;;
        * ) echo "Please answer yes or no.";;
    esac
  done
}

print_and_eval_command() {
  if [ "$1" = "--include-type" ] ; then
    cmd=$2
    maybe_type="\n$(type $2 2> /dev/null)\n"
  else
    cmd=$1
    maybe_type=""
  fi

  # echo -e "${current_command}\nExecuting:\n\n\t$cmd\n$maybe_type"
  echo -e "\nCOMOTO CLI executing...\n\n\t$cmd\n$maybe_type"

  eval $cmd
}

