#!/bin/bash

# TODO combine this with $JJC_CONFIG_DIR/lib?
# TODO rename formatter?

# HELPERS FOR PRINTING OUTPUT TO USER
#######################################

. $JJC_CONFIG_DIR/lib/ansi_color

if [[ -n "$1" ]]; then
  current_command="$1: "
fi

print_info() {
  echo "${current_command}$1"
}

print_header() {
  echo ; print_info "$1"
}

# Expects one argument string, e.g. "Are you sure you want to proceed?"
# Usually used in an if statement, like:
# if print_confirm 'Are you sure you want to proceed?' ; then
#   do_something
# else
#   do_something_else
# fi
print_confirm() {
  while true; do
    read -p "${current_command}$1 [Y/n] " yn
    case $yn in
        [Yy]* ) return 0;;
        [Nn]* ) return 1;;
        * ) echo "Please answer yes or no.";;
    esac
  done
}

print_and_eval_command() {
  if [ "$1" = "--include-type" ] ; then
    cmd=$2
    maybe_type="\n$(type $2 2> /dev/null)\n"
  else
    cmd=$1
    maybe_type=""
  fi

  echo -e "\n${boldon}COMOTO CLI${boldoff} executing...\n\n\t$cmd\n$maybe_type"

  eval $cmd
}

