#!/bin/bash

# TODO rename this file to comoto_cli.bash?
# TODO somewhere in all bash stuff I source the zla bash helpers twice. Rectify.


# Add moto script to path
export COMOTO_CLI_ROOT="$JJC_CONFIG_DIR/comoto_cli"

# TODO this shouldn't be hardcoded in here
# TODO rename COMOTO_PROJECT_ROOT?
export COMOTO_PROJECTS_DIR="$HOME/projects/comoto"
export COMOTO_PROJECT_ROOT=$COMOTO_PROJECTS_DIR


# TODO this shouldn't live here..
alias cdc="cd $COMOTO_PROJECT_ROOT"

# Set up github cli command completion
eval "$(gh completion -s bash)"

echo_help() {
  # TODO make this a command (non-exexcutable)
  echo "TODO: flesh out this help message"
  exit 0
}

# https://github.com/icy/bash-coding-style#function-names
# TODO see https://revzilla.atlassian.net/wiki/spaces/TECH/pages/338919566/Kubernetes+and+Google+Cloud+-+Getting+Started
# TODO https://github.com/revzilla/monorepo/wiki/Dev-Ops

comoto_cli() {
  if [[ $# -eq 0 ]] || [[ $# -eq 1 &&  $1 =~ ^(-h|--help)$  ]] ; then
    echo "no args!"
    echo_help
  fi

  local command="$1"
  # Run command if valid or throw error
  potential_command_path="$COMOTO_CLI_ROOT/command/$command"
  shift
  if [[ -f $potential_command_path ]] ; then
    unset -f _comoto_cli_command_execute
    . $potential_command_path
    _comoto_cli_command_execute $@
  else
    echo "No such command '$command' (TODO: improve error msg)" >&2
    return 1
  fi
}

alias moto=comoto_cli
alias m=comoto_cli

export -f comoto_cli

_comoto_cli_completion() {
  # https://devmanual.gentoo.org/tasks-reference/completion/index.html

  if [[ $COMP_CWORD -eq 1 ]] ; then
    local cur_word="$2"
    COMPREPLY=( $(compgen -W "$(ls $COMOTO_CLI_ROOT/command)" -- "$cur_word"))
    return 0
  fi

  local cur_command="${COMP_WORDS[1]}"
  local cur_command_path="$COMOTO_CLI_ROOT/command/$cur_command"
  if [[ -f $cur_command_path ]] ; then
    unset _comoto_cli_command_completion
    . $cur_command_path
    _comoto_cli_command_completion "${COMP_WORDS[@]:2}"
  else
    echo -e "\n'${cur_command}' is an invalid command" >&2
  fi
}
complete -F _comoto_cli_completion comoto_cli m
