#!/bin/bash

source $JJC_CONFIG_DIR/_setup/helpers.sh

print_header "AG (i.e. the Silver Searcher)"

print_subheader $JJC_CONFIG_DIR/ag/setup

#######################################
# Install if not already installed

echo 'Looking for ag'
if ag --version &> /dev/null
then
  echo 'Found'
else
  echo 'Not found. Installing.'
  sudo apt install silversearcher-ag
fi


#######################################
# Confirm installation

if ag --version &> /dev/null
then
  print_success 'ag is installed'
else
  print_fail 'ag not installed'
fi
