#!/bin/bash

. $JJC_CONFIG_LIB/headers

command_name=ag

#######################################
# start main script
#######################################

print_header "AG (i.e. the Silver Searcher)"

print_subheader $JJC_CONFIG_ROOT/ag/setup

#######################################
# Install if not already installed

echo 'Looking for ag'
if $JJC_CONFIG_LIB/command_exists $command_name
then
  echo 'Found'
else
  echo 'Not found. Installing.'
  sudo apt install silversearcher-ag
fi

#######################################
# Confirm installation

report_on_installation $command_name
