#!/bin/bash

NVIM_CONFIG_ROOT=$HOME/.config/nvim

# cd into nvim config
alias cdv="cd $NVIM_CONFIG_ROOT"

# open nvim in various directories
alias vi="nvim"
alias viv="cd $NVIM_CONFIG_ROOT;vi;cd -"

# set default editor
export VISUAL=nvim
