#!/bin/bash

# TODO add functions that'll check dialyzer and credo before pushing
# TODO it should also recompile with --warnings-as-errors so I catch those CircleCI dealbreakers

alias jc-logs="cdm && docker-compose logs -f --tail=100 revzilla-redline-webapp"

jc-gitsync()
{

  echo -e "\n------------------------------"
  echo -e "fetching upsteam/master\n"
  git fetch upstream master

  echo -e "\n------------------------------"
  echo -e "checking out master\n"
  git checkout master

  echo -e "\n------------------------------"
  echo -e "merge master with upstream/master\n"
  git merge upstream/master

  echo -e "\n------------------------------"
  echo -e "pushing master\n"
  git push

  echo -e "\n------------------------------"
  echo -e "git all -n 20\n"
  git all -n 20

}

# TODO make the comoto_cli available
source $JJC_CONFIG_DIR/moto/bashrc

# TODO hasn't this been superceded yet?
alias jc-docker="cd_zla && docker-compose stop && docker-compose up -d && jc-logs"

source $(comoto_cli path monorepo)/zlaverse/support/bash_functions.sh
source /usr/share/google-cloud-sdk/completion.bash.inc 2>/dev/null

cg-bash-noninteractive()
{
  # This is the same as `cg-bash` from ~/monorepo/zlaverse/support/bash_functions.sh,
  # just without the -ti flags
  docker exec -u ${ZV_DEPLOY_UID} $ZV_CG bash -lc "$1"
}

jc-format-elixir()
{
  # Expects a single argument: path to file relative to ~/monorepo/redline/
  echo "formatting $1"
  cg-bash-noninteractive "mix format $1"
}

# OTHER
alias cdm='moto cd monorepo'
alias cde='moto cd ecom'
alias cdr='moto cd redline'
# TODO should zla be changed to zlaverse ?
alias cdz='moto cd zla' # the same as cd_zla

# TODO does this work?
jc-dialyzer()
{
  rz-bash mix dialyzer --ignore-exit-status | tee dialyzer.txt
}
