#!/bin/bash

alias cdg="cd ~/projects/gratuitous_greyhound"
alias cdsu="cd ~/projects/gratuitous_greyhound/apps/suns_core"
alias cdst="cd ~/projects/gratuitous_greyhound/apps/statechart"

# Load private env vars
# TODO set this up
source ~/.bashrc_private 2>/dev/null
