#!/bin/bash
# main entry point for my bashrc

# TODO take a look at ben stein's to see what I can steal
# https://gist.github.com/therealbenstein/40bca4fd9f6d365ec3cd491c6091336f
# TODO use apt ... update everything?

########################################
# Source primary bash configs
########################################

script_dir="$( cd -- "$( dirname -- "${BASH_SOURCE[0]:-$0}"; )" &> /dev/null && pwd 2> /dev/null; )";
export JJC_CONFIG_ROOT=$(readlink -f $script_dir/..)
export JJC_CONFIG_LIB="$JJC_CONFIG_ROOT/lib"

. $script_dir/bashrc_general
. $script_dir/bashrc_personal
. $JJC_CONFIG_ROOT/comoto/bashrc

########################################
# Source from other config dirs
########################################

. $JJC_CONFIG_ROOT/ack/bashrc
. $JJC_CONFIG_ROOT/asdf/bashrc
. $JJC_CONFIG_ROOT/elixir/profile
. $JJC_CONFIG_ROOT/git/bashrc
. $JJC_CONFIG_ROOT/keyboard/bashrc
. $JJC_CONFIG_ROOT/neovim/bashrc
. $JJC_CONFIG_ROOT/fd/bashrc
. $JJC_CONFIG_ROOT/fzf/bashrc
. $JJC_CONFIG_ROOT/datagrip/bashrc
