#!/bin/bash

# TODO rename this file ../bashrc/entrypoint/comoto
# TODO maybe while I'm creating all these symlinks... maybe I should just have a symlink at ~/.jjc_config_dir that everything points thru...

# TODO should this be declared here?
export JJC_CONFIG_ROOT="$HOME/projects/config"
. $JJC_CONFIG_ROOT/bash/bashrc
