#!/bin/bash
# main entry point for my bashrc

# TODO take a look at ben stein's to see what I can steal
# https://gist.github.com/therealbenstein/40bca4fd9f6d365ec3cd491c6091336f

########################################
# Source primary bash configs
########################################

script_dir="$( cd -- "$( dirname -- "${BASH_SOURCE[0]:-$0}"; )" &> /dev/null && pwd 2> /dev/null; )";
JJC_CONFIG_DIR=$(readlink -f $script_dir/..)

source $script_dir/bashrc_general
source $script_dir/bashrc_personal
source $script_dir/bashrc_comoto

########################################
# Source from other config dirs
########################################

config_dir=$script_dir/..

# asdf config
source $config_dir/asdf/bashrc

# git config
source $config_dir/git/bashrc

# keyboard bindings like R-Caps-Lock -> R-Crtl
source $config_dir/keyboard/bashrc

# neovim config
source $config_dir/neovim/bashrc

# fzf config
source $config_dir/fzf/bashrc
