#!/bin/bash

# TODO move this to $JJC_CONFIG_DIR/comoto?
# TODO add functions that'll check dialyzer and credo before pushing
# TODO it should also recompile with --warnings-as-errors so I catch those CircleCI dealbreakers

alias jc-logs="comoto_cli cd monorepo && docker-compose logs -f --tail=10 revzilla-redline-webapp"
alias jclogsjp="comoto_cli cd monorepo && docker-compose logs -f --tail=10 jp-cycles-redline-webapp"

jc-gitsync()
{

  echo -e "\n------------------------------"
  echo -e "fetching upsteam/master\n"
  git fetch upstream master

  echo -e "\n------------------------------"
  echo -e "checking out master\n"
  git checkout master

  echo -e "\n------------------------------"
  echo -e "merge master with upstream/master\n"
  git merge upstream/master

  echo -e "\n------------------------------"
  echo -e "pushing master\n"
  git push

  echo -e "\n------------------------------"
  echo -e "git all -n 20\n"
  git all -n 20

}

. $JJC_CONFIG_DIR/comoto_cli/comoto_cli.bash

# TODO hasn't this been superceded yet?
alias jc-docker="cd_zla && docker-compose stop && docker-compose up -d && jc-logs"

# TODO switch this back once m path is fixed
# source $(comoto_cli path monorepo)/zlaverse/support/bash_functions.sh
. $HOME/projects/comoto/monorepo/zlaverse/support/bash_functions.sh
. /usr/share/google-cloud-sdk/completion.bash.inc 2>/dev/null

cg-bash-noninteractive()
{
  # This is the same as `cg-bash` from ~/monorepo/zlaverse/support/bash_functions.sh,
  # just without the -ti flags
  docker exec -u ${ZV_DEPLOY_UID} $ZV_CG bash -lc "$1"
}

jc-format-elixir()
{
  # Expects a single argument: path to file relative to ~/monorepo/redline/
  echo "formatting $1"
  cg-bash-noninteractive "mix format $1"
}

# OTHER
alias cdm='comoto_cli cd monorepo'
alias cde='comoto_cli cd ecom'
alias cdr='comoto_cli cd redline'
# TODO should zla be changed to zlaverse ?
alias cdz='comoto_cli cd zla'

# TODO does this work?
jc-dialyzer()
{
  rz-bash mix dialyzer --ignore-exit-status | tee dialyzer.txt
}
