#!/bin/bash

# .bashrc
# https://devhints.io/bash

. $JJC_CONFIG_LIB/headers

print_header "BASHRC SETUP"

target_path="$JJC_CONFIG_ROOT/bash/bashrc_entry_point_comoto"
symlink_path="~/.bashrc"
$JJC_CONFIG_LIB/create_symlink $target_path $symlink_path
