#!/bin/bash

# .bashrc
# https://devhints.io/bash

bashrc_path=~/.bashrc
script_dir="$( cd -- "$( dirname -- "${BASH_SOURCE[0]:-$0}"; )" &> /dev/null && pwd 2> /dev/null; )";
source $script_dir/../_setup/helpers.sh

RED='\033[0;31m'
CYAN='\033[1;36m'
NC='\033[0m' # No Color

echo -e "${CYAN}\n-----------------------------------------"
echo ".bashrc setup"
echo -e "-----------------------------------------\n${NC}"

echo -e "\n"

if test -f "$bashrc_path"; then
  # Alert user to the fact there's already stuff in the bashrc
  echo -e "$bashrc_path already exists.\n\n-- start of contents --\n"
  cat "$bashrc_path"
  echo -e "\n\n-- end of contents --"

  # Would the user like to first modify the file before adding the generated code?
  echo -e "\nThe following code will be added to the bashrc:"
  echo -e "\n\n#start generated by $script_dir on 20220612 --\nennontseraointsriaotsra\nneotsrnntisroa"
else
  echo "$bashrc_path does NOT exist."
fi

echo -e "I ${RED}love${NC} Stack Overflow"



# SCRIPT_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]:-$0}"; )" &> /dev/null && pwd 2> /dev/null; )";
# echo "$SCRIPT_DIR"
# echo "$BASH_SOURCE"
# echo "$( dirname -- $BASH_SOURCE)"
