#!/bin/bash

# See the README.md

. $JJC_CONFIG_LIB/headers

command_name=fdfind
pretty_print_name=fd
apt_name='fd-find'

command_exists() {
   $JJC_CONFIG_LIB/command_exists $command_name
}

#######################################
# start main script
#######################################

print_header "FD"

# TODO should I be using `apt` elsewhere in my config?
# https://itsfoss.com/apt-vs-apt-get-difference/
# TODO no, apparently you should be using the old apt-get instead
command_exists || sudo apt install $apt_name

# Print success or failure
# TODO add pretty-print variable
report_on_installation -p $pretty_print_name $command_name
